CREATE TABLE IF NOT EXISTS orders
(id INTEGER PRIMARY KEY, type VARCHAR NOT NULL, status VARCHAR NOT NULL, price DECIMAL NOT NULL);



CREATE TABLE IF NOT EXISTS users
(email VARCHAR PRIMARY KEY, firstname VARCHAR NOT NULL,
 lastname VARCHAR NOT NULL, role VARCHAR NOT NULL, longiude DECIMAL, latitude DECIMAL, psw VARCHAR );

